"""Add multi-tenant organization models

Revision ID: 1a14840929e8
Revises: b098830af443
Create Date: 2026-06-22 13:02:09.036895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a14840929e8'
down_revision: Union[str, Sequence[str], None] = 'b098830af443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plantier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'org_admin', 'soc_manager', 'soc_analyst', 'read_only', name='organizationrole'), nullable=False),
    sa.Column('invitation_token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_invitation_token'), 'organization_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'org_admin', 'soc_manager', 'soc_analyst', 'read_only', name='organizationrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branding_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_prefs_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('organization_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scans_processed', sa.Integer(), nullable=False),
    sa.Column('copilot_queries', sa.Integer(), nullable=False),
    sa.Column('reports_generated', sa.Integer(), nullable=False),
    sa.Column('investigations_created', sa.Integer(), nullable=False),
    sa.Column('graph_queries', sa.Integer(), nullable=False),
    sa.Column('storage_bytes', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('api_keys', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('api_keys', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_org_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.add_column('email_scans', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index('ix_email_scans_org_scanned_at', 'email_scans', ['organization_id', 'scanned_at'], unique=False)
    op.create_index(op.f('ix_email_scans_organization_id'), 'email_scans', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'email_scans', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('investigations', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index('ix_inv_org_created_at', 'investigations', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_organization_id'), 'investigations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'investigations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('relationships', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_relationships_user_id'), table_name='relationships')
    op.create_index(op.f('ix_relationships_organization_id'), 'relationships', ['organization_id'], unique=False)
    op.drop_constraint(op.f('relationships_user_id_fkey'), 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('relationships', 'user_id')
    op.add_column('reports', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index('ix_reports_org_created_at', 'reports', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('threat_campaigns', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index('ix_campaign_org_created_at', 'threat_campaigns', ['organization_id', 'first_seen'], unique=False)
    op.create_index(op.f('ix_threat_campaigns_organization_id'), 'threat_campaigns', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'threat_campaigns', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('threat_intel_cache', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_threat_intel_cache_organization_id'), 'threat_intel_cache', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'threat_intel_cache', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_intel_cache', type_='foreignkey')
    op.drop_index(op.f('ix_threat_intel_cache_organization_id'), table_name='threat_intel_cache')
    op.drop_column('threat_intel_cache', 'organization_id')
    op.drop_constraint(None, 'threat_campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_threat_campaigns_organization_id'), table_name='threat_campaigns')
    op.drop_index('ix_campaign_org_created_at', table_name='threat_campaigns')
    op.drop_column('threat_campaigns', 'organization_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index('ix_reports_org_created_at', table_name='reports')
    op.drop_column('reports', 'organization_id')
    op.add_column('relationships', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key(op.f('relationships_user_id_fkey'), 'relationships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_relationships_organization_id'), table_name='relationships')
    op.create_index(op.f('ix_relationships_user_id'), 'relationships', ['user_id'], unique=False)
    op.drop_column('relationships', 'organization_id')
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_index(op.f('ix_investigations_organization_id'), table_name='investigations')
    op.drop_index('ix_inv_org_created_at', table_name='investigations')
    op.drop_column('investigations', 'organization_id')
    op.drop_constraint(None, 'email_scans', type_='foreignkey')
    op.drop_index(op.f('ix_email_scans_organization_id'), table_name='email_scans')
    op.drop_index('ix_email_scans_org_scanned_at', table_name='email_scans')
    op.drop_column('email_scans', 'organization_id')
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index('ix_audit_org_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'organization_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('api_keys', 'permissions')
    op.drop_column('api_keys', 'organization_id')
    op.drop_table('organization_usage')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invitation_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
