"""Add user_id to relationships

Revision ID: 96c8e0285fbe
Revises: a5e69aeccec1
Create Date: 2026-06-21 23:46:13.020115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c8e0285fbe'
down_revision: Union[str, Sequence[str], None] = 'a5e69aeccec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('relationships', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_relationships_user_id'), 'relationships', ['user_id'], unique=False)
    op.create_foreign_key(None, 'relationships', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Backfill user_id where Relationship is directly connected to a scan
    op.execute("""
        UPDATE relationships r
        SET user_id = s.user_id
        FROM email_scans s
        WHERE r.source_type = 'scan' AND r.source_value = s.id::text;
    """)
    op.execute("""
        UPDATE relationships r
        SET user_id = s.user_id
        FROM email_scans s
        WHERE r.target_type = 'scan' AND r.target_value = s.id::text;
    """)

    # Delete any orphaned relationships (e.g. ones that can't be mapped directly)
    op.execute("DELETE FROM relationships WHERE user_id IS NULL;")

    # Alter column to be NOT NULL
    op.alter_column('relationships', 'user_id', existing_type=sa.UUID(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_index(op.f('ix_relationships_user_id'), table_name='relationships')
    op.drop_column('relationships', 'user_id')
    # ### end Alembic commands ###
