"""Add threat hunting indexes

Revision ID: a5e69aeccec1
Revises: 
Create Date: 2026-06-21 18:42:35.313412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e69aeccec1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Enum('email', 'domain', 'sender', 'url', 'attachment', 'campaign', 'ip_address', 'threat_actor', name='nodetype'), nullable=False),
    sa.Column('node_value', sa.String(length=2048), nullable=False),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_graph_nodes_node_value'), 'knowledge_graph_nodes', ['node_value'], unique=False)
    op.create_table('threat_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('indicators', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'monitoring', name='campaignstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_intel_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_type', sa.Enum('url', 'domain', 'ip', 'hash', name='indicatortype'), nullable=False),
    sa.Column('indicator_value', sa.String(length=2048), nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_cache_indicator_value'), 'threat_intel_cache', ['indicator_value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('email_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('sender_display_name', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('return_path', sa.String(length=320), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('parsed_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('mime_structure', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('safe', 'low', 'suspicious', 'high', name='risklevel'), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('risk_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('investigation_report', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'analyzing', 'completed', 'failed', name='scanstatus'), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scans_attack_type'), 'email_scans', ['attack_type'], unique=False)
    op.create_index(op.f('ix_email_scans_scanned_at'), 'email_scans', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_email_scans_sender_address'), 'email_scans', ['sender_address'], unique=False)
    op.create_index(op.f('ix_email_scans_status'), 'email_scans', ['status'], unique=False)
    op.create_table('knowledge_graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('attack_classification', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('severity_level', sa.Enum('low', 'medium', 'high', 'critical', name='severitylevel'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('tactics_detected', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_output', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ioc_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('investigation_summary', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('technical_summary', sa.Text(), nullable=False),
    sa.Column('attack_chain', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('analyst_notes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('attachment_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('md5_hash', sa.String(length=32), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_executable', sa.Boolean(), nullable=False),
    sa.Column('has_macros', sa.Boolean(), nullable=False),
    sa.Column('is_double_extension', sa.Boolean(), nullable=False),
    sa.Column('file_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_analyses_md5_hash'), 'attachment_analyses', ['md5_hash'], unique=False)
    op.create_index(op.f('ix_attachment_analyses_sha256_hash'), 'attachment_analyses', ['sha256_hash'], unique=False)
    op.create_table('email_iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.Enum('domain', 'subdomain', 'url', 'ip', 'email', 'md5', 'sha1', 'sha256', 'attachment_name', 'attachment_extension', 'sender_domain', 'reply_to_domain', 'message_id', 'phone_number', 'cryptocurrency_wallet', name='ioctype'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('reputation_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_iocs_scan_id'), 'email_iocs', ['scan_id'], unique=False)
    op.create_index(op.f('ix_email_iocs_value'), 'email_iocs', ['value'], unique=False)
    op.create_table('header_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('spf_pass', sa.Boolean(), nullable=True),
    sa.Column('spf_result', sa.String(length=50), nullable=False),
    sa.Column('dkim_pass', sa.Boolean(), nullable=True),
    sa.Column('dkim_result', sa.String(length=50), nullable=False),
    sa.Column('dmarc_pass', sa.Boolean(), nullable=True),
    sa.Column('dmarc_result', sa.String(length=50), nullable=False),
    sa.Column('sender_spoofed', sa.Boolean(), nullable=False),
    sa.Column('display_name_impersonation', sa.Boolean(), nullable=False),
    sa.Column('domain_mismatch', sa.Boolean(), nullable=False),
    sa.Column('relay_chain', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('forged_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bec_indicators', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('executive', 'technical', 'incident', 'compliance', name='reporttype'), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'json', 'html', name='reportformat'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('domain_age_days', sa.Integer(), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('whois_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('redirect_chain', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_shortened', sa.Boolean(), nullable=False),
    sa.Column('is_homoglyph', sa.Boolean(), nullable=False),
    sa.Column('is_typosquatting', sa.Boolean(), nullable=False),
    sa.Column('is_ip_based', sa.Boolean(), nullable=False),
    sa.Column('tld', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threat_intel_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_analyses_domain'), 'url_analyses', ['domain'], unique=False)
    op.create_index(op.f('ix_url_analyses_original_url'), 'url_analyses', ['original_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_analyses_original_url'), table_name='url_analyses')
    op.drop_index(op.f('ix_url_analyses_domain'), table_name='url_analyses')
    op.drop_table('url_analyses')
    op.drop_table('scan_reports')
    op.drop_table('header_analyses')
    op.drop_index(op.f('ix_email_iocs_value'), table_name='email_iocs')
    op.drop_index(op.f('ix_email_iocs_scan_id'), table_name='email_iocs')
    op.drop_table('email_iocs')
    op.drop_index(op.f('ix_attachment_analyses_sha256_hash'), table_name='attachment_analyses')
    op.drop_index(op.f('ix_attachment_analyses_md5_hash'), table_name='attachment_analyses')
    op.drop_table('attachment_analyses')
    op.drop_table('ai_analyses')
    op.drop_table('knowledge_graph_edges')
    op.drop_index(op.f('ix_email_scans_status'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_sender_address'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_scanned_at'), table_name='email_scans')
    op.drop_index(op.f('ix_email_scans_attack_type'), table_name='email_scans')
    op.drop_table('email_scans')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_intel_cache_indicator_value'), table_name='threat_intel_cache')
    op.drop_table('threat_intel_cache')
    op.drop_table('threat_campaigns')
    op.drop_index(op.f('ix_knowledge_graph_nodes_node_value'), table_name='knowledge_graph_nodes')
    op.drop_table('knowledge_graph_nodes')
    # ### end Alembic commands ###
