"""Add detections to email_scans

Revision ID: aa8eea711b96
Revises: 96c8e0285fbe
Create Date: 2026-06-21 23:50:16.825035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8eea711b96'
down_revision: Union[str, Sequence[str], None] = '96c8e0285fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_scans', sa.Column('detections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('email_scans', 'mime_structure',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_scans', 'mime_structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('email_scans', 'detections')
    # ### end Alembic commands ###
