"""Add Report model with polymorphic associations

Revision ID: b098830af443
Revises: aa8eea711b96
Create Date: 2026-06-22 12:25:49.283028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b098830af443'
down_revision: Union[str, Sequence[str], None] = 'aa8eea711b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_reports')
    op.execute("DROP TYPE IF EXISTS reporttype CASCADE")
    op.execute("DROP TYPE IF EXISTS reportformat CASCADE")
    op.execute("DROP TYPE IF EXISTS reportstatus CASCADE")
    
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('scan', 'investigation', 'campaign', 'threat_actor', 'executive', name='reporttype'), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'json', 'html', name='reportformat'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='reportstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_type', postgresql.ENUM('executive', 'technical', 'incident', 'compliance', name='reporttype'), autoincrement=False, nullable=False),
    sa.Column('format', postgresql.ENUM('pdf', 'json', 'html', name='reportformat'), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], name=op.f('scan_reports_scan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('scan_reports_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scan_reports_pkey'))
    )
    op.drop_table('reports')
    # ### end Alembic commands ###
